#*******************************************************************************
# IBM Confidential
# OCO Source Materials
# 5737-J29, 5737-B18
# (C) Copyright IBM Corp. 2020 All Rights Reserved.
# The source code for this program is not  published or otherwise divested of
# its trade secrets, irrespective of what has been deposited with
# the U.S. Copyright Office.
#*******************************************************************************

apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: ibpcas.ibp.com
  labels:
    app.kubernetes.io/instance: ibm-hlfsupport-ca
    app.kubernetes.io/managed-by: ibm-hlfsupport-operator
    app.kubernetes.io/name: ibm-hlfsupport
    helm.sh/chart: ibm-hlfsupport
    release: operator
spec:
  conversion:
    strategy: Webhook
    webhook:
      conversionReviewVersions: ["v1beta1", "v1alpha2", "v1alpha1"]
      clientConfig:
        service:
          namespace: ibpinfra
          name: ibp-webhook
          path: /crdconvert
        caBundle: "${TLS_CERT}"
  group: ibp.com
  names:
    kind: IBPCA
    listKind: IBPCAList
    plural: ibpcas
    singular: ibpca
  scope: Namespaced
  versions:
  - name: v1beta1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            x-kubernetes-preserve-unknown-fields: true
            type: object
          status:
            x-kubernetes-preserve-unknown-fields: true
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
  - name: v1alpha2
    schema:
      openAPIV3Schema:
        properties:
          spec:
            x-kubernetes-preserve-unknown-fields: true
            type: object
          status:
            x-kubernetes-preserve-unknown-fields: true
            type: object
        type: object
    served: true
    storage: false
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            x-kubernetes-preserve-unknown-fields: true
            type: object
          status:
            x-kubernetes-preserve-unknown-fields: true
            type: object
        type: object
    served: true
    storage: false
  - name: v210
    schema:
      openAPIV3Schema:
        properties:
          spec:
            x-kubernetes-preserve-unknown-fields: true
            type: object
          status:
            x-kubernetes-preserve-unknown-fields: true
            type: object
        type: object
    served: false
    storage: false
  - name: v212
    schema:
      openAPIV3Schema:
        properties:
          spec:
            x-kubernetes-preserve-unknown-fields: true
            type: object
          status:
            x-kubernetes-preserve-unknown-fields: true
            type: object
        type: object
    served: false
    storage: false
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []